# -*- coding: utf-8 -*-
"""Escape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrXm0ISQQSQUqBU01uww8Km3XEL32_5W
"""

print ('dia berkata: "pergilah!"')

print ("aku menimpali: \"apakah kau ingin aku 'angkat kaki'?!\"")

print ("\\(^_^)/ (\\-_-/)")

