# -*- coding: utf-8 -*-
"""File Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sbB4x8MuXtn2R_puuZg4z74Q2nFEjpf

TUGAS FILE HANDLING
*   DWI ANDINI
*   2411012033
"""

import requests

# 1. ambil data api
url = "https://api.open-meteo.com/v1/forecast?latitude=-5.45&longitude=105.27&daily=temperature_2m_max,temperature_2m_min,precipitation_sum&timezone=Asia%2FBangkok"

res = requests.get(url)
data = res.json()

print("Status:", res.status_code)

# 2. buka file (append)
file = open("data_cuaca.txt", "a")

# ambil datanya
tanggal = data['daily']['time']
tmax = data['daily']['temperature_2m_max']
tmin = data['daily']['temperature_2m_min']
hujan = data['daily']['precipitation_sum']

print("Data cuaca:\n")

# 3. loop
for i in range(len(tanggal)):

    # 4. kondisi
    if hujan[i] > 0:

        if hujan[i] > 20:
            cuaca = "Hujan Lebat"
        else:
            cuaca = "Hujan Ringan"

        hasil = "Tanggal: " + tanggal[i] + "\n"
        hasil += "Suhu: " + str(tmin[i]) + " - " + str(tmax[i]) + "\n"
        hasil += "Hujan: " + str(hujan[i]) + " mm\n"
        hasil += "Cuaca: " + cuaca + "\n"
        hasil += "------------------------\n"

        print(hasil)
        file.write(hasil)