# -*- coding: utf-8 -*-
"""Manipulasi String 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKb824JmN_ovOtVThPQbZIbOpONli9h1

format string
"""

template = 'halo, saya %s dari %s'

print (template % ('lendis fabri', 'indonesia'))

"""fungsi format"""

template = 'halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'

print (template.format(nama = 'lendis fabri', asal = 'indonesia'))
print (template_2.format('nasi goreng', 'air putih'))

"""string interpolation"""

nama = 'lendis fabri'
asal = 'indonesia'

print (f'perkenalkan saya {nama} dari {asal}')

"""memecah string menjadi list dan sebaliknya"""

alamat = 'surabaya, jawa timur, indonesia'

print (alamat.split())
print (alamat.split(','))
print (alamat.split(', '))

print ('❤'.join(['aku','suka','phyton']))
print ('🐕‍🦺'.join(alamat.split(', ')))

"""mengubah string menjadi upper


"""

print ('halo selamat pagi!'.upper())
print ('halo selamat siang!'.upper())

"""mengubah string menjadi lower"""

print ('apa kabar?'.lower())
print ('lagi dimana?'.lower())

"""mengubah string menjadi title"""

print ('daun tidak pernah membenci angin'.title())
print ('LASKAR PELANGI'.title())

"""mengubah string menjadi reverse"""

print ('IIndonesia Negara Kepulauan'.swapcase())
print ('aKu cIntA NegErIkU'.swapcase())

"""mencari kata pada string"""

angka = '12345'

print ('index angka 3:', angka.find('3'))
print ('index angka 45:', angka.find('45'))
print ('index angka 35:', angka.find('35'))

asal = 'lampungu'
print (asal.find ('3'))
print (asal.find ('u'))
print (asal.find ('lam'))
print (asal.find ('pung'))
print (asal.find ('langu'))

"""mereplace kata pada string"""

ibu_kota = 'jakarta'
negara = 'indonesia'

print (negara.replace ('a', 'i'))
print (negara.replace ('i', '❤'))
print (ibu_kota.replace ('a', 'i'))
print (ibu_kota.replace ('k', '🤑'))
print (ibu_kota.replace ('kar','🐕‍🦺'))
print (ibu_kota.replace ('a',''))

"""menghitung jumlah kata pada string"""

paragraf = 'baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x= paragraf.count ('di')
y= paragraf.count ('a')
z= paragraf.count ('i')

print (f'kata "di" muncul sebanyak {x} kali')
print (f'kata "a" muncul sebanyak {y} kali')
print (f'kata "i" muncul sebanyak {z} kali')