# -*- coding: utf-8 -*-
"""Manipulasi String-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SR0BU8bdJWpnHD15TkAPP1pp8IrZCtla

operasi pada string
"""

berita = 'ramai-ramai developer di seluruh dunia mulai menggunakan \
teks editor masa kini seperti visual studio code, \
atom, sublime text, dan lain sebagainya.'

print('sublime text' in berita)  # output: True
print('notepad++' in berita)     # output: False

"""memotong string"""

nama = 'lendis febri'
print (nama[4]) # output:i
print (nama[7]) # output:f
print (nama[-1]) # output:i
print (nama[-3]) # output: b

"""slicing string"""

judul = 'pelajaran matematika untuk sd'

print (judul[0:5]) # output:pelaj
print (judul[:10]) # output:pelajaran
print (judul[10:15]) # output:matem
print (judul[-1:-3]) # output:
print (judul[:-3]) # output:pelajaran matematika untuk
print (judul[-5:]) # output:uk sd

"""menghitung panjang string"""

print (len('indonesia')) #output:9
print (len('malaysia')) #output:8

"""memeriksa karakter awal string"""

nomor_telepon_1 = '0871122334455'
nomor_telepon_2 = '6288776655300'
nomor_telepon_3 = '+6233003300330'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara)) #false
print(nomor_telepon_2.startswith(kode_negara)) #false
print(nomor_telepon_3.startswith(kode_negara)) #true

"""memeriksa karakter akhir string"""

email_1 = 'presiden@gmail.com'
email_2 = 'presiden@outlook.com'

print(email_1.endswith('@gmail.com')) #true
print(email_2.endswith('@gmail.com')) #false