# -*- coding: utf-8 -*-
"""Tipe Data Casting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c47XRPG0TABXs18JQNU6tEgAVCDwfC0V

tipe data casting
"""

nama ='lendis febri'
print (type(nama))

"""memeriksa jenis tipe data"""

nama = 'budi'
usia = 20
lajang = True

print (type(nama))
print (type(usia))
print (type(lajang))

"""konversi tipe data"""

usia = input ('masukkan usia anda: ')
print (type(usia))

panjang = int(input ('masukkan panjang:'))
lebar = int(input ('masukkan lebar:'))

print ('luas=', panjang*lebar)

"""konversi tipe data secara implisit"""

a = 10/2
print (type(a))

b = 1/2
print (type(b))

kata = 'jeruk'*5

print (kata)
print (type(kata))

"""konversi tipe data secara eksplisit"""

list() = untuk list
set() = untuk set
tuple() = untuk tuple
dict() = untuk dictionary

"""konversi string ke numerik"""

panjang = int(input ('masukkan panjang:'))
lebar = float(input ('masukkan lebar:'))

print ('luas=', panjang*lebar)

nama = 'widi'
tahun_lahir = 2000

print(nama + 'lahir di tahun' + str (tahun_lahir))